HackathonApp/HackathonApp/Controllers/GamesHistoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HackathonApp.Business;
using HackathonApp.Common;
using HackathonApp.Models;

namespace HackathonApp.Controllers
{
    public class GamesHistoryController : Controller
    {
        private readonly IGameLogRepository gameLogRepo;
        private readonly IPlayerRatingRepository playerRatingRepo;

        public GamesHistoryController(IGameLogRepository gameLogRepo, IPlayerRatingRepository playerRatingRepo)
        {
            this.gameLogRepo = gameLogRepo;
            this.playerRatingRepo = playerRatingRepo;
        }


        // GET: GamesHistory
        public ActionResult Index()
        {
            return View(playerRatingRepo.GetTopTen());
        }

        public ActionResult MyGames()
        {
            string userLogin = GeneralSettings.UseDatabase ? User.Identity.Name : "Player1";
            var model = gameLogRepo.GetMyHistory(userLogin).Select(i => TransformViewItem(i, userLogin));

            return View(model);
        }

        private MyGameHistoryGameModelItem TransformViewItem(GameLog log, string userLogin)
        {
            var result = new MyGameHistoryGameModelItem();
            result.Time = log.GameEnded;

            if (log.Player1 == userLogin)
            {
                result.Oponent = log.Player2;
                result.Result = GetResultString(log.Player1Result);
                result.RowClass = GetResultRowClass(log.Player1Result);
            }
            else
            {
                result.Oponent = log.Player1;
                result.Result = GetResultString(log.Player2Result);
                result.RowClass = GetResultRowClass(log.Player2Result);
            }

            return result;
        }

        private string GetResultString(double result)
        {
            if (result <= 0.1)
            {
                return "lost";
            }
            if (result >= 0.9)
            {
                return "win";
            }
            return "draw";
        }

        private string GetResultRowClass(double result)
        {
            if (result <= 0.1)
            {
                return "table-danger";
            }
            if (result >= 0.9)
            {
                return "table-success";
            }
            return "";
        }

    }
}

HackathonApp/HackathonApp/Views/Shared/ChatComponent.cshtml
<div class="chatPanel">

</div>

HackathonApp/HackathonApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - @HackathonApp.Common.GeneralSettings.ApplicationName</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="@ViewBag.AdditionalClass">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(HackathonApp.Common.GeneralSettings.ApplicationName, "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Game", "Index", "Game")</li>
                    <li>@Html.ActionLink("Top 10", "Index", "GamesHistory")</li>
                    <li>@Html.ActionLink("My Games", "MyGames", "GamesHistory")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    @*<li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @Html.Partial("ChatComponent")
        @RenderBody()
        <footer>
            <p>&copy; @DateTime.Now.Year - Majkl&Bogan dynamic duo</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/jquery.signalR-2.2.2.js"></script>
    <script src="~/signalr/hubs"></script>
    <script src="~/ClientApp/app.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>