HackathonApp/HackathonApp/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HackathonApp.Controllers
{
    [Authorize]
    public class GameController : Controller
    {
        
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Over(Boolean winner)
        {
            return View(winner);
        }
    }
}

HackathonApp/HackathonApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HackathonApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

    }
}

HackathonApp/HackathonApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
    ViewBag.AdditionalClass = "about-site";
}
<div class="jumbotron">
    <h2>@HackathonApp.Common.GeneralSettings.ApplicationName</h2>
    programmed by
    <h3>Majkl&Bogan dynamic duo</h3>
</div>

HackathonApp/HackathonApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

HackathonApp/HackathonApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    ViewBag.AdditionalClass = "home-site";
}

<div class="jumbotron">
    <h1>@HackathonApp.Common.GeneralSettings.ApplicationName</h1>
    <p class="lead">GL HF ...</p>
    <p><a href="@Url.Action("Index", "Game")" class="btn btn-primary btn-lg">Start game</a></p>
</div>